[2024-07-20T03:45:54.781+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-20T03:45:54.800+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_first_pipeline.retrain manual__2024-07-20T03:44:39.332909+00:00 [queued]>
[2024-07-20T03:45:54.807+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_first_pipeline.retrain manual__2024-07-20T03:44:39.332909+00:00 [queued]>
[2024-07-20T03:45:54.808+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-20T03:45:54.831+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): retrain> on 2024-07-20 03:44:39.332909+00:00
[2024-07-20T03:45:54.840+0000] {standard_task_runner.py:64} INFO - Started process 304 to run task
[2024-07-20T03:45:54.843+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'my_first_pipeline', 'retrain', 'manual__2024-07-20T03:44:39.332909+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/dag_examne.py', '--cfg-path', '/tmp/tmp01p59gou']
[2024-07-20T03:45:54.844+0000] {standard_task_runner.py:91} INFO - Job 5: Subtask retrain
[2024-07-20T03:45:54.890+0000] {task_command.py:426} INFO - Running <TaskInstance: my_first_pipeline.retrain manual__2024-07-20T03:44:39.332909+00:00 [running]> on host fb6a10e6c01a
[2024-07-20T03:45:54.959+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='jabier' AIRFLOW_CTX_DAG_ID='my_first_pipeline' AIRFLOW_CTX_TASK_ID='retrain' AIRFLOW_CTX_EXECUTION_DATE='2024-07-20T03:44:39.332909+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-20T03:44:39.332909+00:00'
[2024-07-20T03:45:54.960+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-20T03:46:07.887+0000] {logging_mixin.py:188} WARNING - 2024/07/20 03:46:07 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
[2024-07-20T03:46:09.961+0000] {logging_mixin.py:188} WARNING - /usr/local/lib/python3.11/site-packages/xgboost/core.py:158 UserWarning: [03:46:09] WARNING: /workspace/src/learner.cc:740:
Parameters: { "use_label_encoder" } are not used.
[2024-07-20T03:46:34.651+0000] {logging_mixin.py:188} WARNING - /usr/local/lib/python3.11/site-packages/xgboost/core.py:158 UserWarning: [03:46:34] WARNING: /workspace/src/learner.cc:740:
Parameters: { "use_label_encoder" } are not used.
[2024-07-20T03:47:01.235+0000] {logging_mixin.py:188} WARNING - /usr/local/lib/python3.11/site-packages/xgboost/core.py:158 UserWarning: [03:47:01] WARNING: /workspace/src/learner.cc:740:
Parameters: { "use_label_encoder" } are not used.
[2024-07-20T03:47:26.172+0000] {logging_mixin.py:188} WARNING - /usr/local/lib/python3.11/site-packages/xgboost/core.py:158 UserWarning: [03:47:26] WARNING: /workspace/src/learner.cc:740:
Parameters: { "use_label_encoder" } are not used.
[2024-07-20T03:47:51.805+0000] {logging_mixin.py:188} WARNING - /usr/local/lib/python3.11/site-packages/xgboost/core.py:158 UserWarning: [03:47:51] WARNING: /workspace/src/learner.cc:740:
Parameters: { "use_label_encoder" } are not used.
[2024-07-20T03:48:15.644+0000] {logging_mixin.py:188} INFO - Número de trials: 1
[2024-07-20T03:48:15.644+0000] {logging_mixin.py:188} INFO - AUC PR: 0.2554677541753223
[2024-07-20T03:48:15.645+0000] {logging_mixin.py:188} INFO - Mejores hiperparámetros encontrados:
[2024-07-20T03:48:15.646+0000] {logging_mixin.py:188} INFO - learning_rate: 0.001761429776226269
[2024-07-20T03:48:15.646+0000] {logging_mixin.py:188} INFO - n_estimators: 904
[2024-07-20T03:48:15.647+0000] {logging_mixin.py:188} INFO - max_depth: 5
[2024-07-20T03:48:15.647+0000] {logging_mixin.py:188} INFO - max_leaves: 29
[2024-07-20T03:48:15.648+0000] {logging_mixin.py:188} INFO - min_child_weight: 4
[2024-07-20T03:48:15.648+0000] {logging_mixin.py:188} INFO - reg_alpha: 0.3100988541403896
[2024-07-20T03:48:15.649+0000] {logging_mixin.py:188} INFO - reg_lambda: 0.9666964890585669
[2024-07-20T03:48:15.650+0000] {logging_mixin.py:188} INFO - subsample: 0.8978412565259557
[2024-07-20T03:48:15.650+0000] {logging_mixin.py:188} INFO - colsample_bytree: 0.6092145992622349
[2024-07-20T03:48:15.651+0000] {logging_mixin.py:188} INFO - gamma: 2.627972298937555
[2024-07-20T03:48:15.651+0000] {logging_mixin.py:188} INFO - scale_pos_weight: 7.67386900953956
[2024-07-20T03:48:18.731+0000] {logging_mixin.py:188} WARNING - /usr/local/lib/python3.11/site-packages/xgboost/core.py:158 UserWarning: [03:48:18] WARNING: /workspace/src/learner.cc:740:
Parameters: { "use_label_encoder" } are not used.
[2024-07-20T03:49:24.847+0000] {python.py:237} INFO - Done. Returned value was: xgb_pipeline.joblib
[2024-07-20T03:49:24.848+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-20T03:49:24.869+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=my_first_pipeline, task_id=retrain, run_id=manual__2024-07-20T03:44:39.332909+00:00, execution_date=20240720T034439, start_date=20240720T034554, end_date=20240720T034924
[2024-07-20T03:49:24.968+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-07-20T03:49:24.982+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-07-20T03:49:24.998+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
